### ISSUE TITLE
Gulp 4 support

### ISSUE THREAD

**Issue by heikki** [slushjs/slush#26]
Hi, do you have any thoughts regarding gulp 3/4 support?

I have done some digging in my fork: https://github.com/heikki/slush/tree/4.0
A lot of duplication can be removed because cli logic has now been separated to [gulp-cli](https://github.com/gulpjs/gulp-cli).

**Comment by joakimbeng** [comment]
Slush should definitely have gulp 4 support! I haven't had the time looking at it yet though.

Your work looks promising! I would gladly accept a PR, if you would like to provide one :)

**Comment by heikki** [comment]
Great! Still investigating some things, PR after that.

**Comment by joakimbeng** [comment]
@heikki it would be great if you could make a PR of this to the `v2` branch, even though you're not finished yet?

**Comment by heikki** [comment]
Ok. I keep this on hold until gulp-cli release with gulp 4 support is out.

**Comment by about-code** [comment]
gulp 4 eventually got its [v4.0.0 tag](https://github.com/gulpjs/gulp/tree/v4.0.0) and was [released for comments as `gulp@next` on Jan 1st 2018](https://github.com/gulpjs/gulp/issues/1486#issuecomment-354632417). An official gulp@4.0.0 npm package will follow once the community got some time for testing.

**Comment by demurgos** [comment]
I'm linking a related issue and PR around removing a deprecated dependency (`gulp-util`):
- https://github.com/slushjs/slush/issues/61
- https://github.com/slushjs/slush/pull/62

**Comment by enavarrocu** [comment]
Hello guys, 

Why is this is not going forward? Is almost a year of this issue. What can we do to make this happen? I trying to use this project but I can't go for it without gulp 4 support.

**Comment by joakimbeng** [comment]
I want to make this happen, but I need help! See #64 for the latest discussion...

**Comment by enavarrocu** [comment]
How I can help? I'm not very experienced but maybe I can help.

**Comment by jeantimex** [comment]
I tried to use gulp 4 with slush 1.1.1, when I slush my app, I got the following error:
```
/Users/jeantimex/.nvm/versions/node/v9.10.1/lib/node_modules/slush/bin/slush.js:106
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /Users/jeantimex/.nvm/versions/node/v9.10.1/lib/node_modules/slush/bin/slush.js:106:20
    at process._tickCallback (internal/process/next_tick.js:112:11)
    at Function.Module.runMain (module.js:692:11)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

If I rollback to gulp 3, the error is gone, anyone knows how to get around this? Here is my slush app: https://github.com/jeantimex/slush-html5-app, thanks!
