### ISSUE TITLE
How can I add babel to this?

### ISSUE THREAD

**Issue by dagumak** [slushjs/slush#33]
I tried piping babel in a few places, but could't get it to compile.  Could anyone more familiar with Slush and Gulp point me towards the right direction?

**Comment by amitmtrn** [comment]
@dagumak the question isn't clear. 
Did you tired to create a generator with babel support through [gulp babel](https://www.npmjs.com/package/gulp-babel)?
Please provide an example of what you try to do.

**Comment by joakimbeng** [comment]
After almost a year but still no example code I'm closing this...
