### ISSUE TITLE
Ability to turn off default gulp log messages

### ISSUE THREAD

**Issue by osdevisnot** [slushjs/slush#39]
It would be great addition to add ability to turn off default log messages. Example:
[11:26:28] Starting '..:view'...
[11:26:28] Starting '..:controller'...
[11:26:28] Finished '..:view'... after 0.00 s
[11:26:28] Finished '..:controller'... after 0.00 s

Some references on where gulp does this: https://github.com/gulpjs/gulp/issues/492, https://github.com/gulpjs/gulp/blob/3.7/bin/gulp.js#L91-L93, https://github.com/gulpjs/gulp/blob/3.7/bin/gulp.js#L32

Let me know if I am unclear or any other qq.

**Comment by DJWindless** [comment]
It would be very great, i am searching for hours for a solutions.
