### ISSUE TITLE
Files and folders that are prefixed with an underscore are being converted to dotfiles

### ISSUE THREAD

**Issue by loremipson** [slushjs/slush#41]
It looks like anything I have in my `templates` directory that begins with an underscore ie: `_settings.scss` or `_partials/`, when they are copied over after Slush runs, they're being saved out as: `.settings.scss` or `.partials`

This is pretty restrictive in my use case. Is this an intended feature of Slush or have I possibly done something to cause this?

**Comment by joakimbeng** [comment]
This has nothing to do with `slush` itself, it's caused by the slush-generator you're using. Which generator are you using, i.e. how do you run slush? For instance running `slush angular` executes the `slush-angular` generator...

**Comment by loremipson** [comment]
Ah, yep, it is. I'm using a custom internal generator, but it was built using [slush-generator](https://github.com/chrisenytc/slush-generator), which has that [rename function](https://github.com/chrisenytc/slush-generator/blob/master/templates/slushfile.js#L91) that does exactly what I was running into. Really should have noticed that one myself. Thanks for the help!
