### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by shinzui** [slushjs/slush#42]
Hi,

I am trying to adopt either slush or yeoman for our internal microservices templates. I prefer the simplicity of slush but it looks, based on activity, that the project is abandoned. What's your plan for 2.0? 

Thank you.

**Comment by joakimbeng** [comment]
The project is not abandoned, but I haven't had that much time to invest in this.
One reason for this is that it "just works" ;)
For a [2.0](https://github.com/slushjs/slush/milestones/2.0) I want good composability, and better support for local installed generators (the latter needs [a workaround](https://github.com/slushjs/slush/issues/5#issuecomment-128124919) at the moment, but I have prepared for solving this for real with the [module-finder](https://www.npmjs.com/package/module-finder) module). The [composability](https://github.com/slushjs/slush/issues/13) is a harder nut to crack, I haven't figured out a good way for this and I welcome any ideas on the topic!

**Comment by shinzui** [comment]
That's great. I strongly prefer slush over yeoman. 

Would it make sense to release slush 2 with just gulp 4 support, and later release a 3.0 with support for good composability and locally installed generators?  Decoupling the releases would keep slush current with the latest gulp version.
