### ISSUE TITLE
ES6 template strings unsupported?

### ISSUE THREAD

**Issue by john-goldsmith** [slushjs/slush#47]
Not sure if this is related to #33 or not, but...

Slush seems to blow up when using ES6 template strings in a template file.

``` javascript
// my-slush-generator/templates/main.js
let foo = '';
console.log(`hello ${foo}`);
```

``` shell
$ slush my-slush-generator
events.js:85
      throw er; // Unhandled 'error' event
            ^
ReferenceError: foo is not defined
```

Am I missing something or is this just not supported at the moment?

Thanks for this tool, and keep up the good work!

**Comment by joakimbeng** [comment]
I think it's related to the templating engine you're using, i.e. what gulp plugin are you piping all your template files through?

It's related to [#46](https://github.com/slushjs/slush/issues/46#issuecomment-156689921) where `gulp-template` destroys images.

**Comment by icarcal** [comment]
I had the same issue.

This is "caused" by the gulp-template plugin.
It uses the lodash.template to compile all the tags on your generator files.
This function evaluates the ```<%= %>``` AND the ES6 ```${}``` tags (for more info: https://lodash.com/docs/4.15.0#template)

To change this behavior, just change on your slushfile.js the line
``` .pipe(template(answers)) ```
to
``` .pipe(template(answers, {interpolate: /<%=([\s\S]+?)%>/g}))```

and you should be good to go.
