### ISSUE TITLE
Dotfiles being ignored?

### ISSUE THREAD

**Issue by john-goldsmith** [slushjs/slush#48]
It'd be great if dotfiles could be produced by generators.  This would be helpful for generating files such as `.gitignore`, `.jshintrc`, `.drone.yml`, etc.  Thanks!

**Comment by joakimbeng** [comment]
A generator can already produce dotfiles in two ways:

1. Use the `dot` option for `gulp.src`:

```javascript
// copy all files (including dotfiles from /generator-path/templates to current working directory:
gulp.src('./templates/**', {cwd: __dirname, dot: true})
  .pipe(gulp.dest('./'));
```

2. Use `gulp.src` in combination with [`gulp-rename`](https://www.npmjs.com/package/gulp-rename), see e.g. [`slush-angular`'s slushfile](https://github.com/slushjs/slush-angular/blob/ca4e56484e08eff56cfa4ca3e3f13c62e0c0b5e6/slushfile.js#L60-L66)
