### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mefynn** [slushjs/slush#49]
im getting this strange error after i freshly set up everything. do i have to create some sort of json file for slush to run? happend on all other generators
```
➜  prototype  slush gulp-primer
/usr/local/lib/node_modules/slush-gulp-primer/slushfile.js:50
    authorName: user.name || '',
                    ^

TypeError: Cannot read property 'name' of undefined
```

**Comment by joakimbeng** [comment]
This is not a Slush issue but an issue with the generator you're trying to use. Please file an issue in the `slush-gulp-primer` repo.
