### ISSUE TITLE
Local Slush generators?

### ISSUE THREAD

**Issue by kokujin** [slushjs/slush#5]
When would it be possible to use locally installed Slush generators?

**Comment by majgis** [comment]
I expect the same behavior as gulp...both the generators and slush should be installed locally.  The global slush should only look for the local slush.  The solution that @Eruant suggests doesn't work the moment two projects need to use different versions of a generator.  I was hoping local installation was what slush offered over yeoman.  It is disappointing to see the same requirement of globals.

**Comment by amitmtrn** [comment]
You can `npm -g` in the package folder and it will install it globally without upload it to npm

**Comment by andreasgrimm** [comment]
any news on this one?

**Comment by joakimbeng** [comment]
Until slush is looking for both local and global generators by default a good workaround is to install both slush and the generators locally, e.g: `npm install --save-dev slush slush-angular`.
By adding `node_modules/.bin` to your PATH calling `slush` will call the local module and also list the local generators.

**Comment by majgis** [comment]
@joakimbeng Thank you for pointing out that a local install does work from npm run scripts (which adds node_modules/.bin to PATH).

Global install `npm i slush slush-angular -g`:
    
    $ slush -v
    [slush] 1.1.1

    $ slush
    [slush] Installed generators
    [slush] └── angular (0.4.5)

    $ slush angular
    [slush] Using slushfile /Users/tmpUser/.nvm/versions/node/v0.12.9/lib/node_modules/slush-angular/slushfile.js
    [18:16:11] Starting 'angular:default'...
    [?] What do you want to name your AngularJS app? (tmp) 

Local install `npm i slush@1.0.0 slush-angular@0.4.0 --save-dev` with `"slush":"slush"` in the scripts section of package.json:

    $ npm run slush -- -v

    > tmp@1.0.0 slush /Users/tmpUser/tmp/tmp
    > slush "-v"

    [slush] 1.0.0

    $ npm run slush

    > tmp@1.0.0 slush /Users/tmpUser/tmp/tmp
    > slush

    [slush] Installed generators
    [slush] └── angular (0.4.0)

    $ npm run slush angular

    > tmp@1.0.0 slush /Users/tmpUser/tmp/tmp
    > slush "angular"

    [slush] Using slushfile /Users/tmpUser/tmp/tmp/node_modules/slush-angular/slushfile.js
    [18:06:24] Starting 'angular:default'...
    [?] What do you want to name your AngularJS app? (tmp) 

I actually really like this behavior.  I wonder if adding this strategy for local generators to the documentation would be enough. 

NOTE: The version of npm shipped with node v0.10 doesn't support this behavior of passing arguments/options to run-scripts.
