### ISSUE TITLE
Add github stars to slush website generator search listing

### ISSUE THREAD

**Issue by iamdevonbutler** [slushjs/slush#55]
When I search for yeoman generators (http://yeoman.io/generators/) there are fields that list the #stars and the #installs for each generator. Helps me know what's legit at a glance. This functionality would be nice on the slush generator search page (http://slushjs.github.io/generators/#/).

**Comment by amitmtrn** [comment]
I think this issue should be open and handled at:
https://github.com/slushjs/slushjs.github.io/issues
