### ISSUE TITLE
Escape template var syntax

### ISSUE THREAD

**Issue by Zeindelf** [slushjs/slush#60]
How can I escape variables call in templates?
I need `<%= someVar %>` syntax for iconfont generate into SASS file.

**Comment by no-more** [comment]
Hello, did you find the solution ?

**Comment by Zeindelf** [comment]
Just found working with Yeoman.
Change `<%= someVar %>` to `<%- someVar %>` (dash to not escape `<` and `>`), and on main file, create a prop with same name with a string value `someVar = '<%= fontName %>'`

**Comment by Zeindelf** [comment]
Yep.
I change `<%= someVar %>` to `<%- someVar %>` (dash to not escape `<` and `>`), and on main file, create a prop with same name with a string value `someVar = '<%= fontName %>'`
